global:
  domain: kkumtree-ms-7a34.panda-ule.ts.net

gitea:
  config:
    server:
      DOMAIN: kkumtree-ms-7a34.panda-ule.ts.net
      PROTOCOL: https
      ROOT_URL: https://kkumtree-ms-7a34.panda-ule.ts.net/_gitea/

ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  hosts:
    - host: kkumtree-ms-7a34.panda-ule.ts.net
      paths:
        - path: /_gitea
          pathType: Prefix
  tls:
    - secretName: gitea-selfsigned-tls
      hosts:
        - kkumtree-ms-7a34.panda-ule.ts.net

tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"

nodeSelector:
  node-role.kubernetes.io/control-plane: ""
