global:
  domain: kkumtree-ms-7a34.panda-ule.ts.net

configs:
  params:
    server.basehref: "/_argocd"
    server.rootpath: "/_argocd"

server:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-pathrough: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      # nginx.ingress.kubernetes.io/rewrite-target: /$2
    # paths:
    #   - /argocd(/|$)(.*)
    pathType: ImplementationSpecific
    # pathType: Prefix
    tls: true

