global:
  domain: kkumtree-ms-7a34.panda-ule.ts.net

configs:
  params:
    server.basehref: "/_argocd"
    server.rootpath: _argocd/
  cm:
    url: https://kkumtree-ms-7a34.panda-ule.ts.net/_argocd

server:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    path: /_argocd/
    pathType: Prefix
    tls: true

