apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.image.containerPort }}
      targetPort: {{ .Values.image.containerPort }}
      nodePort: 30000
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
  type: NodePort
